name: Miniforge Installation Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-installation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    defaults:
      run:
        # Use a login shell to ensure conda is available after initialization
        shell: bash -l {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run make setup (Install Miniforge)
      # Override default shell for this step as conda is not yet installed
      shell: bash
      run: make setup

    - name: Initialize Conda (Linux/macOS)
      run: |
        # Set path to the correct conda executable based on OS
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          CONDA_PATH="$HOME/miniforge3/bin"
        elif [[ "${{ runner.os }}" == "macOS" ]]; then
          # On macOS, Homebrew installs it to /opt/homebrew/bin
          CONDA_PATH="/opt/homebrew/bin"
        fi
        
        # Prepend the new conda path for this step and for subsequent steps
        echo "$CONDA_PATH" >> $GITHUB_PATH
        export PATH="$CONDA_PATH:$PATH"
        
        # Initialize the correct conda installation
        conda init bash

    - name: Verify Miniforge Installation
      run: |
        echo "Conda executable: $(which conda)"
        conda --version
        conda info | grep "conda-forge"

    - name: Create Conda Environment
      shell: bash
      run: |
        make create-conda-env
        
        echo "--- Verifying environment ---"
        conda run -n ai-data-broker-remover conda env list | grep "ai-data-broker-remover"
        conda run -n ai-data-broker-remover python --version | grep "3.13"

    - name: Run Tests with uv
      shell: bash
      run: |
        conda run -n ai-data-broker-remover which uv
        conda run -n ai-data-broker-remover which pytest
        conda run -n ai-data-broker-remover uv run pytest
